// 13-React/day-07-Redux/03-src-react中国直接使用redux的问题/App.js
import React,{Component} from 'react'
import store from './redux/store'

export default class App extends Component{
    componentDidMount(){
        store.subscribe(()=>{
            console.log(store.getState().count)
        })
    }

    handle = () =>{
        store.dispatch({type:'INCREMENT',data:1})
    }
    render(){
        return(
            <div>
                <div>{store.getState().count}</div>
                <button onClick = {this.handle}>按钮+1</button>
            </div>
        ) 

    }
}

// 14-Vue/day-06/vue-vuex/src_vuex加法/App.vue
<template>
  <div>
    <p>click {{ $store.state.count }} times count is {{$store.getters.countType}}</p>
    <button @click="increment">+</button>
    <button @click="decrement">-</button>
    <button @click="oddnum">increment if odd</button>
    <button @click="asyncnum">increment async</button>
  </div>
</template>

<script>
export default {
  name: "App",
  mounted() {
    console.log(this.$store);
  },
  methods: {
    increment() {
      this.$store.dispatch("increment");
    },
    decrement() {
      this.$store.dispatch("decrement");
    },
    oddnum() {
      this.$store.dispatch("oddnum");
    },
    asyncnum() {
      this.$store.dispatch("asyncnum");
    },
  },
};
</script>

<style>
</style>
