// 16.Vue电商PC项目/1026-vue/src/App.vue
<template>
  <div>
    <Header />
    <router-view></router-view>

    <Footer v-if="!$route.meta.isHideFooter" />
  </div>
</template>

<script>
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export default {
  name: 'APP',
  components:{
    Header,
    Footer,
  }
}
</script>

<style lang="less" scoped>

</style>

// 13-React/day-02/02-myproject/02-src-函数组件和类组件/App.js
import React from 'react'

import Header from './components/Header'
import Footer from './components/Footer'
import Test from './components/Test'

class App extends React.Component{
    render(){
    return (
        <div id='app'>
            <Header></Header>
            <Footer></Footer>
            <Test />
        </div>
        )
    }
}
