// 14-Vue/day_04/vue-project/src插槽/App.vue
<template>
  <div>
    <p>App...</p>
    <A>
      <p>这是一段文字</p>
      <button>按钮</button>
    </A>
    <B>
      <template #header>
        <header>header...</header>
      </template>

      <template #footer>
        <div>div...</div>
        <footer>footer...</footer>
      </template>
    </B>
    <C>
      <template #content="{ count }">
        <p>count的值：{{ count }}</p>
      </template>
    </C>
  </div>
</template>

<script>
import A from './A'
import B from './B'
import C from './C'


export default{
  name:'App',
  components:{
    A,
    B,
    C,
  }
}
</script>

<style>

</style>

// 13-React/day-02/02-myproject/02-src-函数组件和类组件/App.js
import React from 'react'

import Header from './components/Header'
import Footer from './components/Footer'
import Test from './components/Test'

class App extends React.Component{
    render(){
    return (
        <div id='app'>
            <Header></Header>
            <Footer></Footer>
            <Test />
        </div>
        )
    }
}
