// 13-React/day-08/01-src-users-git案例/pages/Search/index.jsx
import React, { Component } from 'react'

import PubSub from 'pubsub-js'
import { TOPIC } from '../../constans'

export default class Search extends Component {
  state = { searchName: '' }

  handleChange = e => {
    this.setState({
      searchName: e.target.value.trim()
    })
  }

  handleClick = () => {
    PubSub.publish(TOPIC, this.state.searchName)
  }
  handleAllClick = ()=>{

  }
  handleSetionClick = ()=>{
    
  }
  render() {
    return (
      <section className='jumbotron'>
        <h3 className='jumbotron-heading'>Search Github Users</h3>
        <div>
          <input
            type='text'
            placeholder='enter the name you search'
            value={this.state.searchName}
            onChange={this.handleChange}
          />
          <button onClick={this.handleClick}>Search</button>
        </div>
      </section>
    )
  }
}

// 14-Vue/day_04/vue-project/src/Views/Search/index.vue
<template>
  <section class="jumbotron">
    <h3 class="jumbotron-heading">Search Github Users</h3>
    <div>
      <input
        type="text"
        placeholder="enter the name you search"
        v-model="searchName"
      />
      <button @click="sendSearchName">Search</button>
    </div>
  </section>
</template>

<script>
export default {
  name: "Search",
  data() {
    return {
      searchName: "",
      oldSearchName: "",
    };
  },
  methods: {
    sendSearchName() {
      const searchName = this.searchName.trim();
      if (!searchName) {
        alert("请输入搜索内容~");
        return;
      }
      if (this.oldSearchName === searchName) {
        return;
      }
      this.$bus.$emit('sendSearchName', searchName);
      this.oldSearchName = searchName;
    },
  },
};
</script>

<style>
</style>
