// 13-React/day-02/02-组件/03-src'操作类数组的状态/App.js
import React from 'react'

class App extends React.Component{
    //定义状态
    constructor(){
        super()
        this.state = {
            count:0,
            msg:'xixi'
        }
    }
    render(){
        //render 中的this 一定指向当前实例
        return (
            <div id = 'app'>
                <div>{this.state.count}</div>
                <div>{this.state.msg}</div>
                <button onClick={()=>{
                   this.setState({
                       count:this.state.count + 1
                   })        
                }}>按钮</button>
                <Header></Header>
                <Footer></Footer>
                <Test />
            </div>
        )
    }
}
export default App

// 14-Vue/day_04/vue-project/src插槽/App.vue
<template>
  <div>
    <p>App...</p>
    <A>
      <p>这是一段文字</p>
      <button>按钮</button>
    </A>
    <B>
      <template #header>
        <header>header...</header>
      </template>

      <template #footer>
        <div>div...</div>
        <footer>footer...</footer>
      </template>
    </B>
    <C>
      <template #content="{ count }">
        <p>count的值：{{ count }}</p>
      </template>
    </C>
  </div>
</template>

<script>
import A from './A'
import B from './B'
import C from './C'


export default{
  name:'App',
  components:{
    A,
    B,
    C,
  }
}
</script>

<style>

</style>
