// 14-Vue/day_03/todo-list/src/views/Footer/index.vue
<template>
  <div class="todo-footer">
    <label>
      <input type="checkbox" />
    </label>
    <span>
      <span>已完成0</span> / 全部2
    </span>
    <button class="btn btn-danger" >
      清除已完成任务
    </button>
  </div>
</template>

<script>
export default{
    name:'Footer',

}
</script>

<style>
.todo-footer {
  height: 40px;
  line-height: 40px;
  padding-left: 6px;
  margin-top: 5px;
}

.todo-footer label {
  display: inline-block;
  margin-right: 20px;
  cursor: pointer;
}

.todo-footer label input {
  position: relative;
  top: -1px;
  vertical-align: middle;
  margin-right: 5px;
}

.todo-footer button {
  float: right;
  margin-top: 5px;
}
</style>

// 13-React/day-02/02-myproject/src/components/Footer/Footer.js
import React ,{Component} from 'react'
import './Footer.css'

export default class Footer extends Component{
    render(){
        return(
            <div className="todo-footer">
            <label>
              <input type="checkbox"/>
            </label>
            <span>
              <span>已完成0</span> / 全部2
            </span>
            <button className="btn btn-danger">清除已完成任务</button>
          </div>
        )
    }
}
