// 14-Vue/day_04/vue-project/src/Views/List/index.vue
<template>
  <div>
    <h2 v-if="isShowText">请输入搜素内容</h2>
    <h2 v-else-if="isLoading">loading...</h2>
    <div class="row" v-else>
      <div class="card" v-for="user in users" :key="user.id">
        <a :href="user.html_url" target="_blank">
          <img :src="user.avatar_url" style="width: 100px" />
        </a>
        <p class="card-text">{{ user.login }}</p>
      </div>
    </div>
  </div>
</template>

<script>
import axios from "axios";

export default {
  name: "List",
  data() {
    return {
      isShowText: true, // 决定初始化文字显示/隐藏
      isLoading: false, // 决定loading显示/隐藏
      users: [], // 用户列表数据
    };
  },
  mounted() {
    this.$bus.$on("sendSearchName", this.search);
  },
  methods: {
    search(searchName) {

      this.isShowText = false;
      this.isLoading = true;
      // 发送请求
      axios
        .get(`/api/search/users?q=${searchName}`)
        .then((res) => {
          this.isLoading = false;
          this.users = res.data.items.map((user) => {
            return {
              id: user.id,
              login: user.login,
              avatar_url: user.avatar_url,
              html_url: user.html_url,
            };
          });
        })
        .catch((error) => {
          if (error.message === "Network Error") {
            alert("网络链接失败，请打开网络链接或连上WIFI试试");
          }
        });
    },
  },
};
</script>

<style>
</style>

// 13-React/day-08/01-src-users-git案例/pages/List/index.jsx
//最上面一般引入一些三方包
import React, { Component } from 'react'
import PubSub from 'pubsub-js'
import axios from 'axios'

// 中间引入一些自己定义的包
import { TOPIC } from '../../constans'

// 最后引入样式
import './index.css'

export default class List extends Component {


  state = {
    users: [], // 获取到的用户列表
  }
  //挂载成功,订阅话题
  componentDidMount() {
    //这个token,有没有必要加到state中?
    //没有必要,因为token跟试图渲染无关
    this.token = PubSub.subscribe(TOPIC, (msg, data) => {
      // console.log('接收到数据', data)

      if (data.length === 0) return
      // 发送请求
     
      axios
        .get('http://localhost:5000/search/users', {
          params: {
            searchname: data
          }
        })
        .then(res => {
          console.log(res)
          this.setState({
            users: res.data.items,
            loading: false
          })
        })
       
    })
  }

  // 卸载的时候取消订阅
  componentWillUnmount() {
    PubSub.unsubscribe(this.token)
  }
  render() {
    let { users ,flag} = this.state
    if(flag==='ray'){
      users = users.filter((item)=>{
        return item.login ==='ray'
      })
    }
    if (users.length > 0) {
      return (
        <>
          <div>
          <button onClick={this.handle('all')}>All</button>
          <button onClick={this.handle('ray')}>Ray</button>
          </div>
          <div className='row'>
            {this.state.users.map(user => (
              <div className='card' key={user.id}>
                <a  target='_blank'>
                  <img
                    alt=''
                    src={user.avatar_url}
                    style={{ width: 100, height: 100 }}
                  />
                </a>
                <p className='card-text'>{user.login}</p>
              </div>
            ))}
          </div>
        </>

      )
    }

    // 什么都不渲染,就return 一个 null
    return null
  }
}
